#! /bin/bash

low=1
count=0

while [ $low -eq 1 ]
do
echo "Start the limit :"
read low
done



echo "Enter the Nth limit :"
read upper


for n in `seq $low $upper`
do
a=$(factor $n | grep $n | cut -d " " -f 2)


if [ "$a" -eq "$n" ]
then
echo "$n is prime"
((count++))
fi
done

echo  "There are $count number of prime numbers"

